export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_COUNTRY_BY_NAME = "GET_COUNTRY_BY_NAME";
export const GET_COUNTRY_BY_ID= "GET_COUNTRY_BY_ID";
export const FILTER_BY_CONTINENT ="FILTER_BY_CONTINENT";
export const FILTER_BY_ALF ="FILTER_BY_ALF";
export const ORDER_BY_AREA = "ORDER_BY_AREA";
export const GET_ALL_ACTIVITIES = "GET_ALL_ACTIVITIES";
export const FILTER_ACTIVITY = "FILTER_ACTIVITY"